src/api/urls.py
from django.conf import settings
from django.conf.urls import handler404,handler500,handler403,handler400
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flats
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.static import serve

from rest_framework import routers, views, serializers, status
from rest_framework.response import Response
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework_jwt.views import obtain_jwt_token

from src.api.views import viewset
from src.api.views.views import UserCreate, LoginAPI, UserAPI, CheckEmail, CheckUsername, UpdateViews

router = routers.DefaultRouter()
router.register(r'answers', viewset.AnswersViewSet)
router.register(r'brands', viewset.BrandsViewSet)
router.register(r'carousel-images', viewset.FrontendCarouselImageViewSet)
router.register(r'carousels', viewset.FrontendCarouselViewSet)
router.register(r'categories', viewset.CategoryViewSet)
router.register(r'colors', viewset.ColorViewSet)
router.register(r'comments', viewset.BlogPostCommetViewSet)
router.register(r'departments', viewset.DepartmentViewSet)
router.register(r'flatpages', viewset.FlatpagesViewSet)
router.register(r'groups', viewset.GroupViewSet)
router.register(r'lines', viewset.LineViewSet)
router.register(r'page-positions', viewset.PositionViewSet)
router.register(r'flat-pages', viewset.FlatpagesViewSet)
router.register(r'pages', viewset.PagesViewSet)
router.register(r'photos', viewset.PhotoViewSet)
router.register(r'posts', viewset.PublicBlogPostViewSet)
router.register(r'products', viewset.ArticleViewSet)
router.register(r'providers', viewset.ProviderViewSet)
router.register(r'questions', viewset.QuestionsViewSet)
router.register(r'services', viewset.ServiceViewSet)
router.register(r'site', viewset.SiteViewSet)
router.register(r'social-media', viewset.SocialMediaViewSet)
router.register(r'sub-lines', viewset.SubLineViewSet)
router.register(r'tags', viewset.BlogTagViewSet)
router.register(r'testimonials', viewset.TestimonialViewSet)
router.register(r'types', viewset.TypeViewSet)
router.register(r'types', viewset.TypeViewSet)
router.register(r'users', viewset.UserViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    # Token
    # path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('token/auth/', obtain_jwt_token),
    # path('/update-views/', UpdateViews, name='update-view'),
    # Auth
    # path('auth/user/', UserAPI.as_view(), name='register'),
    path('auth/register/', UserCreate.as_view(), name='register'),
    path('auth/login/', LoginAPI.as_view(), name='token_obtain_pair'),
    path('auth/check-email/', CheckEmail, name='register'),
    path('auth/check-username/', CheckUsername, name='register'),
    # path('/', include('rest_framework.urls', namespace='rest_framework')),
]

src/base/urls.py
from django.urls import path, re_path, include
from .views import Home,Contact,Search,\
    ContactThanks,ContactError,session

app_name = 'front'
urlpatterns = [
    # path('', Home, name='home'),
    path('', Home.as_view(), name='home'),
    # path('contacto/gracias', Home, name='contact_thanks'),
    path('contacto/gracias', ContactThanks.as_view(), name='contact_thanks'),
    # path('contacto', Home, name='contact'),
    path('contacto', Contact.as_view(), name='contact'),
    # path('contacto/error', Home, name='contact_error'),
    path('contacto/error', ContactError.as_view(), name='contact_error'),
    # path('busqueda', Home, name='search'),
    path('busqueda', Search.as_view(), name='search'),
    # path('session', Home, name='session'),
    path('session', session, name='session'),
]

src/blog/urls.py
from django.urls import path, re_path, include
from .views import (
    Home,
    BlogDetail,
    comment_create,
)

app_name = 'blog'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('gracias', Home.as_view(), name='thanks'),
    path('<slug:slug>', BlogDetail.as_view(), name='blog_detail'),
    path('<slug:slug>/comentario/crear', comment_create, name='add_comment'),
]

src/intra/urls.py
from django.urls import (path, re_path, include)
from src.intra.views.base import *
from src.intra.views.blog import *
from src.intra.views.multimedia import *
from src.intra.views.sales import *
from src.intra.views.services import *
from src.intra.views.support import *
from src.intra.views.users import *

app_name = 'intra'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    
    path('blogs', Blog.as_view(), name='blog'),
    path('my-posts', MyBlog.as_view(), name='my-blog'),
    path('agregar/blog', BlogCreate.as_view(), name='blog-create'),
    path('actualizar/blog/<int:pk>/', BlogUpdate.as_view(), name='blog-update'),
    path('eliminar/blog/<int:pk>/', BlogDelete.as_view(), name='blog-delete'),

    path('comentarios', Comments.as_view(), name='comments'),
    path('agregar/comentario', CommentCreate.as_view(), name='comment-create'),
    path('actualizar/comentario/<int:pk>/', CommentUpdate.as_view(), name='comment-update'),
    path('eliminar/comentario/<int:pk>/', CommentDelete.as_view(), name='comment-delete'),

    path('etiquetas', Tags.as_view(), name='tags'),
    path('agregar/etiqueta', TagCreate.as_view(), name='tag-create'),
    path('actualizar/etiqueta/<int:pk>/', TagUpdate.as_view(), name='tag-update'),
    path('eliminar/etiqueta/<int:pk>/', TagDelete.as_view(), name='tag-delete'),

    path('configuraciones', Conf.as_view(), name='conf'),
    path('agregar/configuraciones', ConfCreate.as_view(), name='conf-create'),
    path('actualizar/configuraciones/<int:pk>/', ConfUpdate.as_view(), name='conf-update'),
    path('eliminar/configuraciones/<int:pk>/', ConfDelete.as_view(), name='conf-delete'),
    
    path('configuraciones/paginas', ConfPages.as_view(), name='conf-pages'),
    path('agregar/pagina', ConfPageCreate.as_view(), name='conf-page-create'),
    path('actualizar/pagina/<int:pk>/', ConfPageUpdate.as_view(), name='conf-page-update'),
    path('eliminar/pagina/<int:pk>/', ConfPageDelete.as_view(), name='conf-page-delete'),

    path('configuraciones/carruseles', ConfSlides.as_view(), name='conf-slides'),
    path('agregar/carrusel', ConfSlideCreate.as_view(), name='conf-slide-create'),
    path('actualizar/carrusel/<int:pk>/', ConfSlideUpdate.as_view(), name='conf-slide-update'),
    path('eliminar/carrusel/<int:pk>/', ConfSlideDelete.as_view(), name='conf-slide-delete'),
    path('agregar/carrusel-image', ConfSlideImgCreate.as_view(), name='conf-slide-img-create'),
    path('actualizar/carrusel-image/<int:pk>/', ConfSlideImgUpdate.as_view(), name='conf-slide-img-update'),
    path('eliminar/carrusel-image/<int:pk>/', ConfSlideImgDelete.as_view(), name='conf-slide-img-delete'),

    path('configuraciones/faq', ConfFAQS.as_view(), name='conf-faqs'),
    path('agregar/pregunta', ConfFAQQuestionCreate.as_view(), name='conf-faq-question-create'),
    path('actualizar/pregunta/<int:pk>/', ConfFAQQuestionUpdate.as_view(), name='conf-faq-question-update'),
    path('eliminar/pregunta/<int:pk>/', ConfFAQQuestionDelete.as_view(), name='conf-faq-question-delete'),
    path('agregar/respuesta', ConfFAQAnswerCreate.as_view(), name='conf-faq-answer-create'),
    path('actualizar/respuesta/<int:pk>/', ConfFAQAnswerUpdate.as_view(), name='conf-faq-answer-update'),
    path('eliminar/respuesta/<int:pk>/', ConfFAQAnswerDelete.as_view(), name='conf-faq-answer-delete'),

    path('configuraciones/newsletters', ConfNewsletters.as_view(), name='conf-newsletters'),
    path('agregar/newsletter', ConfNewsletterCreate.as_view(), name='conf-newsletter-create'),
    path('actualizar/newsletter/<int:pk>/', ConfNewsletterUpdate.as_view(), name='conf-newsletter-update'),
    path('eliminar/newsletter/<int:pk>/', ConfNewsletterDelete.as_view(), name='conf-newsletter-delete'),

    path('multimedias/', Medias.as_view(), name='medias'),
    path('agregar/multimedia', MediaCreate.as_view(), name='media-create'),
    path('actualizar/multimedia/<int:pk>/', MediaUpdate.as_view(), name='media-update'),
    path('eliminar/multimedia/<int:pk>/', MediaDelete.as_view(), name='media-delete'),

    path('perfil', Profile.as_view(), name='profile'),
    path('usuarios', Users.as_view(), name='users'),
    path('agregar/usuario', UserCreate.as_view(), name='user-create'),
    path('actualizar/usuario/<int:pk>/', UserUpdate.as_view(), name='user-update'),
    path('eliminar/usuario/<int:pk>/', UserDelete.as_view(), name='user-delete'),

    path('productos', Products.as_view(), name='products'),
    path('productos/top', TopProducts.as_view(), name='products-top'),
    path('agregar/producto', ProductCreate.as_view(), name='product-create'),
    path('actualizar/producto/<int:pk>/', ProductUpdate.as_view(), name='product-update'),
    path('eliminar/producto/<int:pk>/', ProductDelete.as_view(), name='product-delete'),

    path('productos/lineas', ProductLines.as_view(), name='products-lines'),
    path('agregar/linea', LineCreate.as_view(), name='line-create'),
    path('actualizar/linea/<int:pk>/', LineUpdate.as_view(), name='line-update'),
    path('eliminar/linea/<int:pk>/', LineDelete.as_view(), name='line-delete'),

    path('productos/sub-lineas', ProductSubLines.as_view(), name='products-sublines'),
    path('agregar/sublinea/', SubLineCreate.as_view(), name='subline-create'),
    path('actualizar/sub-linea/<int:pk>/', SubLineUpdate.as_view(), name='subline-update'),
    path('eliminar/sub-linea/<int:pk>/', SubLineDelete.as_view(), name='subline-delete'),
    
    path('productos/colores', ProductColor.as_view(), name='products-colors'),
    path('agregar/color', ColorCreate.as_view(), name='color-create'),
    path('actualizar/color/<int:pk>/', ColorUpdate.as_view(), name='color-update'),
    path('eliminar/color/<int:pk>/', ColorDelete.as_view(), name='color-delete'),
    
    path('productos/marcas', ProductBrand.as_view(), name='products-brands'),
    path('agregar/marca', BrandCreate.as_view(), name='brand-create'),
    path('actualizar/marca/<int:pk>/', BrandUpdate.as_view(), name='brand-update'),
    path('eliminar/marca/<int:pk>/', BrandDelete.as_view(), name='brand-delete'),
    
    path('productos/categorias', ProductCategory.as_view(), name='products-categories'),
    path('agregar/categoria', CategoryCreate.as_view(), name='category-create'),
    path('actualizar/categoria/<int:pk>/', CategoryUpdate.as_view(), name='category-update'),
    path('eliminar/categoria/<int:pk>/', CategoryDelete.as_view(), name='category-delete'),
    
    path('productos/departamentos', ProductDepartment.as_view(), name='products-departments'),
    path('agregar/departamento', DepartmentCreate.as_view(), name='department-create'),
    path('actualizar/departamento/<int:pk>/', DepartmentUpdate.as_view(), name='department-update'),
    path('eliminar/departamento/<int:pk>/', DepartmentDelete.as_view(), name='department-delete'),

    path('servicios', Services.as_view(), name='services'),    
    path('agregar/servicio', ServiceCreate.as_view(), name='service-create'),
    path('actualizar/servicio/<int:pk>/', ServiceUpdate.as_view(), name='service-update'),
    path('eliminar/servicio/<int:pk>/', ServiceDelete.as_view(), name='service-delete'),
    path('agregar/servicio-img', ServiceIMGCreate.as_view(), name='service-img-create'),
    path('actualizar/servicio-img/<int:pk>/', ServiceIMGUpdate.as_view(), name='service-img-update'),
    path('eliminar/servicio-img/<int:pk>/', ServiceIMGDelete.as_view(), name='service-img-delete'),

    path('soporte', Support.as_view(), name='support'),
]

src/user/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include

from .views import custom_login,custom_logout,custom_register, \
    ActivateAccountView, modal_cookie, error, thanks, newsletter,\
    activate, current_user, UserList

app_name = 'auth'
urlpatterns = [
    path('modal', modal_cookie, name='modal-cookie'),
    path('error', error, name='error'),
    path('newsletter', newsletter, name='newsletter'),
    path('gracias', thanks, name='thanks'),
    path('login/', custom_login, name='login'),
    path('salir/', custom_logout, name='logout'),
    path('registro/', custom_register, name='register'),
    path('password_reset/done/', auth_views.password_reset_done, 
        name='password_reset_done'
    ),
    path('password_reset_complete/done/', auth_views.password_reset_complete, 
        name='password_reset_complete'
    ),
    path('password_reset/', auth_views.password_reset, {
        'post_reset_redirect':'auth:password_reset_done',}, name='password_reset'
    ),
    re_path(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, 
        {
            'post_reset_redirect':'auth:password_reset_complete'
        },
        name='password_reset_confirm'
    ),
    re_path(r'^activar-cuenta/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ActivateAccountView.as_view(), name='activate_account'
    ),
    re_path(r'^activar/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'
    ),
    
    # JWT
    path('current_user/', current_user),
    path('users/', UserList.as_view()),
    
]

src/base/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=144, label='Nombre',)
    email = forms.CharField(max_length=144, label='Correo electronico',)
    subject = forms.CharField(max_length=144, label='Asunto',)
    message = forms.CharField(max_length=744, label='Mensaje',)

templates/app/base/basic_upload.html
{% block javascript %}
{# JQUERY FILE UPLOAD SCRIPTS #}
<script src="{% static 'base/js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'base/js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'base/js/jquery-file-upload/jquery.fileupload.js' %}"></script>

{# PHOTOS PAGE SCRIPTS #}
<script src="{% static 'base/js/basic-upload.js' %}"></script>
{% endblock %}

templates/app/base/error.html
{% extends 'app/base/index.html' %}{% load staticfiles %}

{% block css %}
<style>
        #blog{
        padding-top: 125px !important;
        background-color:unset;
    }
</style>
{% endblock %}

{% block full_screen %}

{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="py-4" id="blog">
        <h2 class="h1 text-center mb-5">Se ha producido un error</h2>
        <p class="text-center mb-5 pb-5">
            Bienvenidos a <span>{{SITE_TITLE}}</span>
        </p>
        <p class="text-center">ir a <span><a href="{% url 'front:home' %}">Inicio</a></span></p>
    </div>
</div>
{% endblock %}

{% block js %}
{% endblock %}

templates/app/base/index.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="es">
<head>
    {% include 'app/base/head.html' %}
    <title>{{SITE_TITLE}} - {{SITE_URL}}</title>
    <script src="{% static 'base/js/jquery-3.2.1.min.js' %}"></script>
    {% block css %}{% endblock %}
</head>
<body>
    {% block full_screen %}{% endblock %}
    {% include 'app/base/nav.html' %}
    {% include 'app/base/social_media.html' %}
    <section id="top-section">
        <div class="content">
        {% block content %}{% endblock %}
        </div>
    </section>
    {% include 'app/base/footer.html' %}
    {% include 'app/base/scripts.html' %}
    {% block js %}{% endblock %}
</body>
</html>

templates/app/base/message.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}

templates/app/base/nav.html
{% load staticfiles %}
<div class="has-background-white" style="z-index:92;">
    <nav class="navbar is-fixed-top  has-background-transparent is-hidden-touch" id="authNavbar">
        <div class="container">
            <div class="navbar-menu">
                <div class="navbar-end">
                    <a href="{% url 'front:contact' %}" class="is-uppercase is-size-7 has-text-black">
                        <span class="icon has-text-black tooltip is-tooltip-left" data-tooltip="Contáctenos">
                            <i class="fas fa-phone"></i>
                        </span>
                        +(507) 800 MOBY
                    </a>
                    <div class="iis-fullnav-auth">
                    {% if user.is_authenticated %}
                        {# if user.is_staff #}
                        <a href="{% url 'intra:home' %}" class="is-uppercase is-size-7 has-text-black">
                            <span class="icon has-text-black tooltip is-tooltip-bottom" data-tooltip="Intranet">
                                <i class="fas fa-sign-in-alt"></i>
                            </span>
                            Intra
                        </a>
                        {# endif #}
                        <a href="{% url 'auth:logout' %}?next={{ request.path }}" class="is-uppercase is-size-7 has-text-black">
                            <span class="icon has-text-black tooltip is-tooltip-bottom" data-tooltip="Cerrar sesión">
                                <i class="fas fa-user-plus"></i>
                            </span>
                            Salir
                        </a>
                    {% else %}
                        <a href="{% url 'auth:login' %}?next={{ request.path }}" class="is-uppercase is-size-7 has-text-black">
                            <spanclass="icon has-text-black tooltip is-tooltip-bottom" data-tooltip="Iniciar sesión">
                                <i class="fas fa-sign-in-alt"></i>
                            </span>
                            Iniciar sesión
                        </a>
                        <a href="{% url 'auth:register' %}?next={{ request.path }}" class="is-uppercase is-size-7 has-text-black">
                            <span class="icon has-text-black tooltip is-tooltip-bottom" data-tooltip="Registrarse">
                                <i class="fas fa-user-plus"></i>
                            </span>
                            Registrarse
                        </a>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <nav class="navbar is-fixed-top has-navbar-gradient" id="fullNavbar">
        <div class="container">
            <div class="navbar-brand">
                <a href="{% url 'front:home' %}" class="navbar-item">
                    <img src="https://s3.us-east-2.amazonaws.com/moby-images-bucket/static/base/img/logo.png" alt="{{SITE_TITLE}}" id="is-logo"></img>
                </a>
                <span class="navbar-burger" ref="isBurger" data-target="navMenu">
                    <span></span>
                    <span></span>
                    <span></span>
                </span>
            </div>
            <div id="navMenu" class="navbar-menu">
                <div class="navbar-end is-hidden-touch">
                    {% for item in FRONT_HEADER_MENU %}
                    <a data-target="navMenu" href="{{item.url}}" class="is-uppercase navbar-item is-nav-link text-green {% if url_nav == item.name %}selected text-green-active{% endif %}">
                        {% if item.have_icon %}
                        <i class="material-icons">{{item.name}}</i>
                        {% else %} {{item.name}} {% endif %}
                    </a>
                    {% endfor %}
                </div>
                <div class="navbar-end is-hidden-desktop">
                    <a href="{% url 'front:home' %}" class="navbar-item">
                        <img src="https://s3.us-east-2.amazonaws.com/moby-images-bucket/static/base/img/logo.png" alt="{{SITE_TITLE}}" id="is-logo"></img>
                    </a>
                    {% for item in FRONT_HEADER_MENU %}
                    <a data-target="navMenu" href="{{item.url}}" class="is-uppercase navbar-item">
                        {{item.name}}
                    </a>
                    {% endfor %}
                </div>
                <div class="is-hidden-desktop is-fullnav-auth">
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}
                        <a href="{% url 'intra:home' %}" class="is-uppercase is-size-7 has-text-black">
                            <span class="icon has-text-black tooltip is-tooltip-bottom" data-tooltip="Intranet">
                                <i class="fas fa-sign-in-alt"></i>
                            </span>
                            Intra
                        </a>
                        {% endif %}
                        <a href="{% url 'auth:logout' %}?next={{ request.path }}" class="is-uppercase is-size-7 has-text-black">
                            <span class="icon has-text-black tooltip is-tooltip-bottom" data-tooltip="Cerrar sesión">
                                <i class="fas fa-user-plus"></i>
                            </span>
                            Salir
                        </a>
                    {% else %}
                        <a href="{% url 'auth:login' %}?next={{ request.path }}" class="is-uppercase is-size-7 has-text-black">
                            <span class="icon has-text-black tooltip is-tooltip-bottom" data-tooltip="Iniciar sesión">
                                <i class="fas fa-sign-in-alt"></i>
                            </span>
                            Iniciar sesión
                        </a>
    
                        <a href="{% url 'auth:register' %}?next={{ request.path }}" class="is-uppercase is-size-7 has-text-black">
                            <span class="icon has-text-black tooltip is-tooltip-bottom" data-tooltip="Registrarse">
                                <i class="fas fa-user-plus"></i>
                            </span>
                            Registrarse
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</div>

templates/app/base/oldnv.html
<!-- <nav class="navbar navbar-expand-md fixed-top navbar-custom shadow navbar-light bg-light">
    <div class="container">
        <a href="{% url 'front:home' %}" class="navbar-brand">
            <img id="menuLogo" src="{{SITE_LOGO}}" alt="{{SITE_TITLE}}">
        </a>
        <button class="navbar-toggler float-right" type="button" data-toggle="collapse" data-target="#navbar9">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse">
            <ul class="navbar-nav ml-auto navbar-nav-custom-1">
                {% for item in FRONT_HEADER_MENU %}
                <li class="nav-item {% if url_nav == item.name %}text-green-active{% endif %}">
                    <a class="nav-link text-uppercase text-green" href="{{item.url}}">
                        {% if item.have_icon %}
                        <i class="material-icons">{{item.name}}</i>
                        {% else %} {{item.name}} {% endif %}
                    </a>
                </li>
                {% endfor %}
            </ul>
            <ul class="navbar-nav ml-auto navbar-nav-custom-2">
                <li>
                    <a href="{% url 'front:contact' %}" class="">
                        <i class="material-icons">phone</i>
                        <span>+(507) 800 MOBY</span>
                    </a>
                </li>
                {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li>
                    <a href="{% url 'intra:home' %}">
                        <i class="material-icons">launch</i>
                        Panel
                    </a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'auth:logout' %}?next={{ request.path }}">
                        <i class="material-icons">exit_to_app</i>
                        Salir
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'auth:login' %}?next={{ request.path }}">
                        <i class="material-icons">account_circle</i>
                        Inicio de sesión
                    </a>
                </li>
                <li>
                    <a href="{% url 'auth:register' %}?next={{ request.path }}">
                        <i class="material-icons">assignment_ind</i>
                        Registro
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="navbar-collapse collapse" id="navbar9">
    <button type="button" class="close" aria-label="Close" data-toggle="collapse" data-target="#navbar9">
        <span class="close-btn" aria-hidden="true">&times;</span>
    </button>
    <ul class="navbar-nav ml-auto navbar-nav-custom-1">
        {% for item in FRONT_HEADER_MENU %}
        <li class="nav-item">
            <a class="nav-link text-uppercase" href="{{item.url}}">
                {% if item.have_icon %}
                <i class="material-icons">{{item.name}}</i>
                {% else %} {{item.name}} {% endif %}
            </a>
        </li>
        {% endfor %}
    </ul>
    <ul class="navbar-nav ml-auto navbar-nav-custom-2">
        <li>
            <a href="{% url 'front:contact' %}">
                <i class="material-icons">phone</i>
                <span>+(507) 397 9180</span>
            </a>
        </li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'intra:home' %}">
                <i class="material-icons">launch</i>
                Panel
            </a>
        </li>
        <li>
            <a href="{% url 'auth:logout' %}?next={{ request.path }}">
                <i class="material-icons">exit_to_app</i>
                Salir
            </a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'auth:login' %}?next={{ request.path }}">
                <i class="material-icons">account_circle</i>
                Inicio de sesión
            </a>
        </li>
        <li>
            <a href="{% url 'auth:register' %}?next={{ request.path }}">
                <i class="material-icons">assignment_ind</i>
                Registro
            </a>
        </li>
        {% endif %}
    </ul>
</div> -->

templates/app/base/scripts.html
{% load staticfiles %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.sticky/1.0.4/jquery.sticky.js"></script>
<script src="{% static 'base/js/app.min.js' %}"></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-83370429-7"></script>

templates/app/base/thanks.html
{% extends 'app/base/index.html' %}{% load staticfiles %}

{% block css %}
<style>
    #blog{padding-top: 125px !important;background-color:unset;}
</style>
{% endblock %}

{% block full_screen %}

{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="py-4" id="blog">
        <h2 class="h1 text-center mb-5">Gracias por creer en nosotros</h2>
        <p class="text-center mb-5 pb-5">
            Bienvenidos a <span>{{SITE_TITLE}}</span>
        </p>
        <p class="text-center">ir a <span><a href="{% url 'front:home' %}">Inicio</a></span></p>
    </div>
</div>
    
{% endblock %}

{% block js %}
{% endblock %}