src/api/urls.py
from django.conf import settings
from django.conf.urls import handler404,handler500,handler403,handler400
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flats
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.static import serve

from rest_framework import routers, views, serializers, status
from rest_framework.response import Response
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework_jwt.views import obtain_jwt_token

from src.api.views import viewset
from src.api.views.views import UserCreate, LoginAPI, UserAPI, CheckEmail, CheckUsername, UpdateViews

router = routers.DefaultRouter()
router.register(r'answers', viewset.AnswersViewSet)
router.register(r'brands', viewset.BrandsViewSet)
router.register(r'carousel-images', viewset.FrontendCarouselImageViewSet)
router.register(r'carousels', viewset.FrontendCarouselViewSet)
router.register(r'categories', viewset.CategoryViewSet)
router.register(r'colors', viewset.ColorViewSet)
router.register(r'comments', viewset.BlogPostCommetViewSet)
router.register(r'departments', viewset.DepartmentViewSet)
router.register(r'flatpages', viewset.FlatpagesViewSet)
router.register(r'groups', viewset.GroupViewSet)
router.register(r'lines', viewset.LineViewSet)
router.register(r'page-positions', viewset.PositionViewSet)
router.register(r'flat-pages', viewset.FlatpagesViewSet)
router.register(r'pages', viewset.PagesViewSet)
router.register(r'photos', viewset.PhotoViewSet)
router.register(r'posts', viewset.PublicBlogPostViewSet)
router.register(r'products', viewset.ArticleViewSet)
router.register(r'providers', viewset.ProviderViewSet)
router.register(r'questions', viewset.QuestionsViewSet)
router.register(r'services', viewset.ServiceViewSet)
router.register(r'site', viewset.SiteViewSet)
router.register(r'social-media', viewset.SocialMediaViewSet)
router.register(r'sub-lines', viewset.SubLineViewSet)
router.register(r'tags', viewset.BlogTagViewSet)
router.register(r'testimonials', viewset.TestimonialViewSet)
router.register(r'types', viewset.TypeViewSet)
router.register(r'types', viewset.TypeViewSet)
router.register(r'users', viewset.UserViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    # Token
    # path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('token/auth/', obtain_jwt_token),
    # path('/update-views/', UpdateViews, name='update-view'),
    # Auth
    # path('auth/user/', UserAPI.as_view(), name='register'),
    path('auth/register/', UserCreate.as_view(), name='register'),
    path('auth/login/', LoginAPI.as_view(), name='token_obtain_pair'),
    path('auth/check-email/', CheckEmail, name='register'),
    path('auth/check-username/', CheckUsername, name='register'),
    # path('/', include('rest_framework.urls', namespace='rest_framework')),
]

src/base/urls.py
from django.urls import path, re_path, include
from .views import Home,Contact,Search,\
    ContactThanks,ContactError,session

app_name = 'front'
urlpatterns = [
    # path('', Home, name='home'),
    path('', Home.as_view(), name='home'),
    # path('contacto/gracias', Home, name='contact_thanks'),
    path('contacto/gracias', ContactThanks.as_view(), name='contact_thanks'),
    # path('contacto', Home, name='contact'),
    path('contacto', Contact.as_view(), name='contact'),
    # path('contacto/error', Home, name='contact_error'),
    path('contacto/error', ContactError.as_view(), name='contact_error'),
    # path('busqueda', Home, name='search'),
    path('busqueda', Search.as_view(), name='search'),
    # path('session', Home, name='session'),
    path('session', session, name='session'),
]

src/intra/urls.py
from django.urls import (path, re_path, include)
from src.intra.views.base import *
from src.intra.views.blog import *
from src.intra.views.multimedia import *
from src.intra.views.sales import *
from src.intra.views.services import *
from src.intra.views.support import *
from src.intra.views.users import *

app_name = 'intra'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    
    path('blogs', Blog.as_view(), name='blog'),
    path('my-posts', MyBlog.as_view(), name='my-blog'),
    path('agregar/blog', BlogCreate.as_view(), name='blog-create'),
    path('actualizar/blog/<int:pk>/', BlogUpdate.as_view(), name='blog-update'),
    path('eliminar/blog/<int:pk>/', BlogDelete.as_view(), name='blog-delete'),

    path('comentarios', Comments.as_view(), name='comments'),
    path('agregar/comentario', CommentCreate.as_view(), name='comment-create'),
    path('actualizar/comentario/<int:pk>/', CommentUpdate.as_view(), name='comment-update'),
    path('eliminar/comentario/<int:pk>/', CommentDelete.as_view(), name='comment-delete'),

    path('etiquetas', Tags.as_view(), name='tags'),
    path('agregar/etiqueta', TagCreate.as_view(), name='tag-create'),
    path('actualizar/etiqueta/<int:pk>/', TagUpdate.as_view(), name='tag-update'),
    path('eliminar/etiqueta/<int:pk>/', TagDelete.as_view(), name='tag-delete'),

    path('configuraciones', Conf.as_view(), name='conf'),
    path('agregar/configuraciones', ConfCreate.as_view(), name='conf-create'),
    path('actualizar/configuraciones/<int:pk>/', ConfUpdate.as_view(), name='conf-update'),
    path('eliminar/configuraciones/<int:pk>/', ConfDelete.as_view(), name='conf-delete'),
    
    path('configuraciones/paginas', ConfPages.as_view(), name='conf-pages'),
    path('agregar/pagina', ConfPageCreate.as_view(), name='conf-page-create'),
    path('actualizar/pagina/<int:pk>/', ConfPageUpdate.as_view(), name='conf-page-update'),
    path('eliminar/pagina/<int:pk>/', ConfPageDelete.as_view(), name='conf-page-delete'),

    path('configuraciones/carruseles', ConfSlides.as_view(), name='conf-slides'),
    path('agregar/carrusel', ConfSlideCreate.as_view(), name='conf-slide-create'),
    path('actualizar/carrusel/<int:pk>/', ConfSlideUpdate.as_view(), name='conf-slide-update'),
    path('eliminar/carrusel/<int:pk>/', ConfSlideDelete.as_view(), name='conf-slide-delete'),
    path('agregar/carrusel-image', ConfSlideImgCreate.as_view(), name='conf-slide-img-create'),
    path('actualizar/carrusel-image/<int:pk>/', ConfSlideImgUpdate.as_view(), name='conf-slide-img-update'),
    path('eliminar/carrusel-image/<int:pk>/', ConfSlideImgDelete.as_view(), name='conf-slide-img-delete'),

    path('configuraciones/faq', ConfFAQS.as_view(), name='conf-faqs'),
    path('agregar/pregunta', ConfFAQQuestionCreate.as_view(), name='conf-faq-question-create'),
    path('actualizar/pregunta/<int:pk>/', ConfFAQQuestionUpdate.as_view(), name='conf-faq-question-update'),
    path('eliminar/pregunta/<int:pk>/', ConfFAQQuestionDelete.as_view(), name='conf-faq-question-delete'),
    path('agregar/respuesta', ConfFAQAnswerCreate.as_view(), name='conf-faq-answer-create'),
    path('actualizar/respuesta/<int:pk>/', ConfFAQAnswerUpdate.as_view(), name='conf-faq-answer-update'),
    path('eliminar/respuesta/<int:pk>/', ConfFAQAnswerDelete.as_view(), name='conf-faq-answer-delete'),

    path('configuraciones/newsletters', ConfNewsletters.as_view(), name='conf-newsletters'),
    path('agregar/newsletter', ConfNewsletterCreate.as_view(), name='conf-newsletter-create'),
    path('actualizar/newsletter/<int:pk>/', ConfNewsletterUpdate.as_view(), name='conf-newsletter-update'),
    path('eliminar/newsletter/<int:pk>/', ConfNewsletterDelete.as_view(), name='conf-newsletter-delete'),

    path('multimedias/', Medias.as_view(), name='medias'),
    path('agregar/multimedia', MediaCreate.as_view(), name='media-create'),
    path('actualizar/multimedia/<int:pk>/', MediaUpdate.as_view(), name='media-update'),
    path('eliminar/multimedia/<int:pk>/', MediaDelete.as_view(), name='media-delete'),

    path('perfil', Profile.as_view(), name='profile'),
    path('usuarios', Users.as_view(), name='users'),
    path('agregar/usuario', UserCreate.as_view(), name='user-create'),
    path('actualizar/usuario/<int:pk>/', UserUpdate.as_view(), name='user-update'),
    path('eliminar/usuario/<int:pk>/', UserDelete.as_view(), name='user-delete'),

    path('productos', Products.as_view(), name='products'),
    path('productos/top', TopProducts.as_view(), name='products-top'),
    path('agregar/producto', ProductCreate.as_view(), name='product-create'),
    path('actualizar/producto/<int:pk>/', ProductUpdate.as_view(), name='product-update'),
    path('eliminar/producto/<int:pk>/', ProductDelete.as_view(), name='product-delete'),

    path('productos/lineas', ProductLines.as_view(), name='products-lines'),
    path('agregar/linea', LineCreate.as_view(), name='line-create'),
    path('actualizar/linea/<int:pk>/', LineUpdate.as_view(), name='line-update'),
    path('eliminar/linea/<int:pk>/', LineDelete.as_view(), name='line-delete'),

    path('productos/sub-lineas', ProductSubLines.as_view(), name='products-sublines'),
    path('agregar/sublinea/', SubLineCreate.as_view(), name='subline-create'),
    path('actualizar/sub-linea/<int:pk>/', SubLineUpdate.as_view(), name='subline-update'),
    path('eliminar/sub-linea/<int:pk>/', SubLineDelete.as_view(), name='subline-delete'),
    
    path('productos/colores', ProductColor.as_view(), name='products-colors'),
    path('agregar/color', ColorCreate.as_view(), name='color-create'),
    path('actualizar/color/<int:pk>/', ColorUpdate.as_view(), name='color-update'),
    path('eliminar/color/<int:pk>/', ColorDelete.as_view(), name='color-delete'),
    
    path('productos/marcas', ProductBrand.as_view(), name='products-brands'),
    path('agregar/marca', BrandCreate.as_view(), name='brand-create'),
    path('actualizar/marca/<int:pk>/', BrandUpdate.as_view(), name='brand-update'),
    path('eliminar/marca/<int:pk>/', BrandDelete.as_view(), name='brand-delete'),
    
    path('productos/categorias', ProductCategory.as_view(), name='products-categories'),
    path('agregar/categoria', CategoryCreate.as_view(), name='category-create'),
    path('actualizar/categoria/<int:pk>/', CategoryUpdate.as_view(), name='category-update'),
    path('eliminar/categoria/<int:pk>/', CategoryDelete.as_view(), name='category-delete'),
    
    path('productos/departamentos', ProductDepartment.as_view(), name='products-departments'),
    path('agregar/departamento', DepartmentCreate.as_view(), name='department-create'),
    path('actualizar/departamento/<int:pk>/', DepartmentUpdate.as_view(), name='department-update'),
    path('eliminar/departamento/<int:pk>/', DepartmentDelete.as_view(), name='department-delete'),

    path('servicios', Services.as_view(), name='services'),    
    path('agregar/servicio', ServiceCreate.as_view(), name='service-create'),
    path('actualizar/servicio/<int:pk>/', ServiceUpdate.as_view(), name='service-update'),
    path('eliminar/servicio/<int:pk>/', ServiceDelete.as_view(), name='service-delete'),
    path('agregar/servicio-img', ServiceIMGCreate.as_view(), name='service-img-create'),
    path('actualizar/servicio-img/<int:pk>/', ServiceIMGUpdate.as_view(), name='service-img-update'),
    path('eliminar/servicio-img/<int:pk>/', ServiceIMGDelete.as_view(), name='service-img-delete'),

    path('soporte', Support.as_view(), name='support'),
]

src/user/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include

from .views import custom_login,custom_logout,custom_register, \
    ActivateAccountView, modal_cookie, error, thanks, newsletter,\
    activate, current_user, UserList

app_name = 'auth'
urlpatterns = [
    path('modal', modal_cookie, name='modal-cookie'),
    path('error', error, name='error'),
    path('newsletter', newsletter, name='newsletter'),
    path('gracias', thanks, name='thanks'),
    path('login/', custom_login, name='login'),
    path('salir/', custom_logout, name='logout'),
    path('registro/', custom_register, name='register'),
    path('password_reset/done/', auth_views.password_reset_done, 
        name='password_reset_done'
    ),
    path('password_reset_complete/done/', auth_views.password_reset_complete, 
        name='password_reset_complete'
    ),
    path('password_reset/', auth_views.password_reset, {
        'post_reset_redirect':'auth:password_reset_done',}, name='password_reset'
    ),
    re_path(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, 
        {
            'post_reset_redirect':'auth:password_reset_complete'
        },
        name='password_reset_confirm'
    ),
    re_path(r'^activar-cuenta/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ActivateAccountView.as_view(), name='activate_account'
    ),
    re_path(r'^activar/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'
    ),
    
    # JWT
    path('current_user/', current_user),
    path('users/', UserList.as_view()),
    
]

src/base/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=144, label='Nombre',)
    email = forms.CharField(max_length=144, label='Correo electronico',)
    subject = forms.CharField(max_length=144, label='Asunto',)
    message = forms.CharField(max_length=744, label='Mensaje',)

src/intra/views/multimedia.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_text, force_bytes
from django.views.generic import ListView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from src.user.tokens import account_activation_token
from src.blog.models import Post, Comment
from src.services.models import *
from src.ventas.models import *
from src.gallery.models import *



@method_decorator(login_required, name='dispatch')
class Medias(ListView):
    # model =
    # context_object_name = 'boards'
    queryset = ''
    template_name = 'intra/medias.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['SITE_URL'] = 'Multimedia'
        context['APP'] = 'Medias'
        return context


@method_decorator(login_required, name='dispatch')
class MediaCreate(CreateView):
    """
    """
    # model = ''
    fields = ['']
    queryset = ''
    template_name = 'intra/add.html'
    success_url = '/intra/'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class MediaUpdate(UpdateView):
    """
    """
    # model = ''
    fields = ['']
    queryset = ''
    template_name = 'intra/edit.html'
    success_url = '/intra/'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class MediaDelete(DeleteView):
    """
    """
    # model = ''
    fields = ['']
    queryset = ''
    template_name = 'intra/delete.html'
    success_url = '/intra/'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

src/intra/views/support.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_text, force_bytes
from django.views.generic import ListView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from src.user.tokens import account_activation_token
from src.blog.models import Post, Comment
from src.services.models import *
from src.ventas.models import *



@method_decorator(login_required, name='dispatch')
class Support(ListView):
    # model =
    # context_object_name = 'boards'
    queryset = ''
    template_name = 'intra/support.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['SITE_URL'] = 'Soporte'
        context['APP'] = 'Support'
        return context

templates/intra/base/head.html
{% load staticfiles %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="{{SITE_DESCRIPTION}}">
<meta name="author" content="Dev2tech" >
<meta name="msapplication-TileColor" content="#9a8700">
<meta name="theme-color" content="#9a8700">
<meta name="msapplication-TileImage" content="/static/favicon/ms-icon-144x144.png">
<link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
<link rel="manifest" href="/static/favicon/manifest.json">

<link rel="apple-touch-icon" sizes="114x114" href="{% static 'base/img/logo/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'base/img/logo/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'base/img/logo/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'base/img/logo/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'base/img/logo/apple-icon-180x180.png' %}">
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'base/img/logo/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'base/img/logo/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'base/img/logo/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'base/img/logo/apple-icon-76x76.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'base/img/logo/favicon-16x16.png' %}">
<link rel="icon" type="image/png" sizes="192x192" href="{% static 'base/img/logo/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'base/img/logo/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'base/img/logo/favicon-96x96.png' %}">

<link rel="stylesheet" href="{% static 'base/css/slick.css' %}">
<link rel="stylesheet" href="{% static 'base/css/slick-theme.css' %}">
<link rel="stylesheet" href="{% static 'base/css/bulma.min.css' %}">
<link rel="stylesheet" href="{% static 'base/css/app.css' %}">

<link href="https://fonts.googleapis.com/css?family=Sarina" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

templates/intra/base/nav.html
<nav class="navbar is-white">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item brand-text is-uppercase" href="{% url 'intra:home' %}">
                Intra
            </a>
            <div class="navbar-burger burger" data-target="navMenu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div id="navMenu" class="navbar-menu">
            <div class="navbar-start">
                <div class="navbar-item">
                </div>
            </div>
            <div class="navbar-end">
                <div class="navbar-item">
                    <a href="{% url 'auth:logout' %}?next=/" class="navbar-item">
                        <strong>Salir</strong>
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>

templates/intra/base/sedenav.html
{% load staticfiles %}

<aside class="menu is-hidden-mobile is-padding-top-30">
    {% if user.is_staff %}
    <p class="menu-label">Configuración</p>
    <ul class="menu-list">
        <li><a href="{% url 'intra:home' %}" class="{% if menu == 'home' %}is-active{% endif %}"><span class="">Inicio</span></a></li>
        <li><a href="{% url 'intra:conf' %}" class="{% if menu == 'conf' %}is-active{% endif %}"><span class="">Sitio</span></a>
            <ul>
                <li><a href="{% url 'intra:conf-pages' %}" class="{% if menu == 'conf-pages' %}is-active{% endif %}"><span class="">Paginas</span></a></li>
                <li><a href="{% url 'intra:conf-slides' %}" class="{% if menu == 'conf-slides' %}is-active{% endif %}"><span class="">Carruseles</span></a></li>
                <li><a href="{% url 'intra:conf-faqs' %}" class="{% if menu == 'conf-faqs' %}is-active{% endif %}"><span class="">Preguntas Frecuentes</span></a></li>
                <li><a href="{% url 'intra:conf-newsletters' %}" class="{% if menu == 'conf-newsletters' %}is-active{% endif %}"><span class="">Boletín Informativos</span></a></li>
            </ul>
        </li>
    </ul>
    {% endif %}
    <p class="menu-label">Usuarios</p>
    <ul class="menu-list">
        {% if user.is_staff %}
        <li><a href="{% url 'intra:users' %}" class="{% if menu == 'users' %}is-active{% endif %}"><span class="">Todos</span></a></li>
        {% endif %}
        <li><a href="{% url 'intra:profile' %}" class="{% if menu == 'profile' %}is-active{% endif %}"><span class="">Mi Perfil</span></a></li>
    </ul>
    <p class="menu-label">Servicios</p>
    <ul class="menu-list">
        <li><a href="{% url 'intra:services' %}" class="{% if menu == 'services' %}is-active{% endif %}" class="{% if menu == 'services' %}is-active{% endif %}"><span class="">Todos</span></a></li>
    </ul>
    <p class="menu-label">Productos</p>
    <ul class="menu-list">
        <li>
            <a href="{% url 'intra:products' %}" class="{% if menu == 'products' %}is-active{% endif %}"><span class="">Todos</span></a>
            {% if user.is_staff %}
                <ul>
                    <li><a href="{% url 'intra:products-lines' %}" class="{% if menu == 'lines' %}is-active{% endif %}"><span class="">Lineas</span></a></li>
                    <li><a href="{% url 'intra:products-sublines' %}" class="{% if menu == 'sub-lines' %}is-active{% endif %}"><span class="">Sub-lineas</span></a></li>
                    <li><a href="{% url 'intra:products-colors' %}" class="{% if menu == 'colors' %}is-active{% endif %}"><span class="">Colores</span></a></li>
                    <li><a href="{% url 'intra:products-brands' %}" class="{% if menu == 'brands' %}is-active{% endif %}"><span class="">Marcas</span></a></li>
                    <li><a href="{% url 'intra:products-categories' %}" class="{% if menu == 'categories' %}is-active{% endif %}"><span class="">Categorías</span></a></li>
                    <li><a href="{% url 'intra:products-departments' %}" class="{% if menu == 'departments' %}is-active{% endif %}"><span class="">Departamentos</span></a></li>
                </ul>
            {% endif %}
        </li>
        <li><a href="{% url 'intra:products-top' %}" class="{% if menu == 'top-products' %}is-active{% endif %}"><span class="">Top 10</span></a></li>
        
    </ul>
    <p class="menu-label">Blog</p>
    <ul class="menu-list">
        <li><a href="{% url 'intra:blog' %}" class="{% if menu == 'blog' %}is-active{% endif %}"><span class="">Todos</span></a></li>
        {% if user.is_staff %}
        <li><a href="{% url 'intra:my-blog' %}" class="{% if menu == 'my-posts' %}is-active{% endif %}"><span class="">Mis publicaciones</span></a></li>
        {% endif %}
    </ul>
    <p class="menu-label">Comentarios</p>
    <ul class="menu-list">
        {% if user.is_staff %}
        <li><a href="{% url 'intra:comments' %}" class="{% if menu == 'comments' %}is-active{% endif %}"><span class="">Todos</span></a></li>
        {% endif %}
        <li><a href="{% url 'intra:comments' %}" class="{% if menu == 'my-comments' %}is-active{% endif %}"><span class="">Mis comentarios</span></a></li>
    </ul>
    <p class="menu-label">Etiquetas</p>
    <ul class="menu-list">
        <li><a href="{% url 'intra:tags' %}" class="{% if menu == 'tags' %}is-active{% endif %}"><span class="">Todas</span></a></li>
    </ul>
    {% if activated %}
    <p class="menu-label">Multimedia</p>
    <ul class="menu-list">
        <li><a href="{% url 'intra:medias' %}" class="{% if menu == 'multimedia' %}is-active{% endif %}"><span class="">Multimedia</span></a></li>
    </ul>
    <p class="menu-label">Soporte</p>
    <ul class="menu-list">
        <li><a href="{% url 'intra:support' %}" class="{% if menu == 'support' %}is-active{% endif %}"><span class="">Soporte</span></a></li>
    </ul>
    {% endif %}
    <p class="menu-label">
        <a href="{% url 'front:home' %}" class="has-text-black">Salir de Intra</a>
    </p>
</aside>

{% block css %}
<style>
    .blue{background-color: #1e90ff !important;color: #fff;border:1px #1e90ff;}
    .green{background-color: #2ed573 !important;color: #fff;border:1px #2ed573;}
    .green2{background-color: #7bed9f !important;color: #fff;border:1px #7bed9f;}
    .golden{background-color: #eccc68 !important;color: #fff;border:1px #eccc68;}
    .menu-label {
        color: #8F99A3;
        letter-spacing: 1.3;
        font-weight: 700;
    }
    .menu-list a {
        color: #0F1D38;
        font-size: 14px;
        font-weight: 700;
    }
    .menu-list a:hover {
        background-color: transparent;
        color: #276cda;
    }
    .menu-list a.is-active {
        background-color: transparent;
        color: #276cda;
        font-weight: 700;
    }
    </style>
{% endblock %}