src/api/urls.py
from django.conf import settings
from django.conf.urls import handler404,handler500,handler403,handler400
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flats
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.static import serve

from rest_framework import routers, views, serializers, status
from rest_framework.response import Response
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework_jwt.views import obtain_jwt_token

from src.api.views import viewset
from src.api.views.views import UserCreate, LoginAPI, UserAPI, CheckEmail, CheckUsername, UpdateViews

router = routers.DefaultRouter()
router.register(r'answers', viewset.AnswersViewSet)
router.register(r'brands', viewset.BrandsViewSet)
router.register(r'carousel-images', viewset.FrontendCarouselImageViewSet)
router.register(r'carousels', viewset.FrontendCarouselViewSet)
router.register(r'categories', viewset.CategoryViewSet)
router.register(r'colors', viewset.ColorViewSet)
router.register(r'comments', viewset.BlogPostCommetViewSet)
router.register(r'departments', viewset.DepartmentViewSet)
router.register(r'flatpages', viewset.FlatpagesViewSet)
router.register(r'groups', viewset.GroupViewSet)
router.register(r'lines', viewset.LineViewSet)
router.register(r'page-positions', viewset.PositionViewSet)
router.register(r'flat-pages', viewset.FlatpagesViewSet)
router.register(r'pages', viewset.PagesViewSet)
router.register(r'photos', viewset.PhotoViewSet)
router.register(r'posts', viewset.PublicBlogPostViewSet)
router.register(r'products', viewset.ArticleViewSet)
router.register(r'providers', viewset.ProviderViewSet)
router.register(r'questions', viewset.QuestionsViewSet)
router.register(r'services', viewset.ServiceViewSet)
router.register(r'site', viewset.SiteViewSet)
router.register(r'social-media', viewset.SocialMediaViewSet)
router.register(r'sub-lines', viewset.SubLineViewSet)
router.register(r'tags', viewset.BlogTagViewSet)
router.register(r'testimonials', viewset.TestimonialViewSet)
router.register(r'types', viewset.TypeViewSet)
router.register(r'types', viewset.TypeViewSet)
router.register(r'users', viewset.UserViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    # Token
    # path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('token/auth/', obtain_jwt_token),
    # path('/update-views/', UpdateViews, name='update-view'),
    # Auth
    # path('auth/user/', UserAPI.as_view(), name='register'),
    path('auth/register/', UserCreate.as_view(), name='register'),
    path('auth/login/', LoginAPI.as_view(), name='token_obtain_pair'),
    path('auth/check-email/', CheckEmail, name='register'),
    path('auth/check-username/', CheckUsername, name='register'),
    # path('/', include('rest_framework.urls', namespace='rest_framework')),
]

src/blog/urls.py
from django.urls import path, re_path, include
from .views import (
    Home,
    BlogDetail,
    comment_create,
)

app_name = 'blog'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('gracias', Home.as_view(), name='thanks'),
    path('<slug:slug>', BlogDetail.as_view(), name='blog_detail'),
    path('<slug:slug>/comentario/crear', comment_create, name='add_comment'),
]

src/services/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flats
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.static import serve

from django.conf.urls.static import static

from src.base import views as base_views
from rest_framework import routers
from app.urls import rest

from django.urls import (path, re_path, include)
from .views import (
    Home,
    ServiceDetail,
    ServiceThanks,
    ServiceError,
)

app_name = 'services'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('gracias', ServiceThanks.as_view(), name='thanks'),
    path('error', ServiceError.as_view(), name='error'),
    path('<slug:slug>', ServiceDetail.as_view(), name='detail'),
]

src/user/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include

from .views import custom_login,custom_logout,custom_register, \
    ActivateAccountView, modal_cookie, error, thanks, newsletter,\
    activate, current_user, UserList

app_name = 'auth'
urlpatterns = [
    path('modal', modal_cookie, name='modal-cookie'),
    path('error', error, name='error'),
    path('newsletter', newsletter, name='newsletter'),
    path('gracias', thanks, name='thanks'),
    path('login/', custom_login, name='login'),
    path('salir/', custom_logout, name='logout'),
    path('registro/', custom_register, name='register'),
    path('password_reset/done/', auth_views.password_reset_done, 
        name='password_reset_done'
    ),
    path('password_reset_complete/done/', auth_views.password_reset_complete, 
        name='password_reset_complete'
    ),
    path('password_reset/', auth_views.password_reset, {
        'post_reset_redirect':'auth:password_reset_done',}, name='password_reset'
    ),
    re_path(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, 
        {
            'post_reset_redirect':'auth:password_reset_complete'
        },
        name='password_reset_confirm'
    ),
    re_path(r'^activar-cuenta/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ActivateAccountView.as_view(), name='activate_account'
    ),
    re_path(r'^activar/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'
    ),
    
    # JWT
    path('current_user/', current_user),
    path('users/', UserList.as_view()),
    
]

src/ventas/urls.py
from django.urls import (path, re_path, include)
from .views import (
    Home,
    Departments,
    DepartmentDetail,
    ProductsList,
    ProductsDetail,
    BrandView,
    BrandsDetails,
)

app_name = 'sales'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('todos', ProductsList.as_view(), name='all'),
    path('detalles/<slug:slug>', ProductsDetail.as_view(), name='product_detail'),
    
    path('departamentos/', Departments.as_view(), name='departments'),
    path('departamentos/<slug:slug>', DepartmentDetail.as_view(), name='department_detail'),

    path('marcas/', BrandView.as_view(), name='brands'),
    path('marcas/<slug:slug>', BrandsDetails.as_view(), name='brand_detail'),
]

templates/app/detail/blog_detail.html
{% extends 'app/base/index.html' %}{% load staticfiles %}{% load widget_tweaks %}

{% block css %}
<style>
    #blogBox, #commentPostBox{
        background-color: #fff;
        padding: 25px;
        border-radius: 3px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
        transition: all 0.3s cubic-bezier(.25,.8,.25,1);
    }
    #commentPostBox #cke_id_content{
        width: 100% !important;
    }
    #commentBox{
        background-color: #f8f8f8;
        box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
        padding: 25px;
    }
</style>
{% endblock %}

{% block full_screen %}
{% endblock %}
{% block content %}

<div class="container is-padding-y-30">
    <div class="columns">
        <div class="column is-8 is-offset-2 is-padding-top-30">
            <div id="blogBox">
                <div class="view overlay hm-white-slight is-centered">
                    {% if object.img.url != None %}
                        <img class="" src="{{object.img.url}}" alt="{{object.title}}">
                    {% elif object.background.url != None %}
                        <img class="" src="{{object.background.url}}" alt="{{object.title}}">
                    {% else %}
                        <img class="" src="/static/base/img/img-base-m.png" alt="{{object.title}}">
                    {% endif %}
                </div>
                <div class="is-padding-top-20">
                    <h1 class="is-size-3"><strong>{{object.title}}</strong></h1>
                    <p class="">
                        {{object.text| safe}}
                    </p>
                    <p>Escrito por 
                        <a class="font-bold dark-grey-text">{{object.author}}</a>, {{object.created_at}}
                    </p>
                    <a href="{{object.get_absolute_url}}" class="btn btn-outline-dark btn-md">Leer más</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container is-padding-y-30">
    {% if has_comments %}
    {% for object in comments %}
        <div class="columns">
        <div class="column is-8 is-offset-2 is-padding-top-10">
            <div id="commentBox">
                <article class="media">
                    <figure class="media-left">
                        <p class="image is-64x64">
                        <img src="https://bulma.io/images/placeholders/128x128.png">
                        </p>
                    </figure>
                    <div class="media-content">
                        <div class="content">
                        <p>
                            <strong>@{{object.author}}</strong> <small>31m</small>
                            <br>
                            {{ object.content|safe }}
                        </p>
                        </div>
                        <nav class="level is-mobile">
                        <!-- <div class="level-left">
                            <a class="level-item">
                            <span class="icon is-small"><i class="fas fa-reply"></i></span>
                            </a>
                            <a class="level-item">
                            <span class="icon is-small"><i class="fas fa-retweet"></i></span>
                            </a>
                            <a class="level-item">
                            <span class="icon is-small"><i class="fas fa-heart"></i></span>
                            </a>
                        </div> -->
                        </nav>
                    </div>
                    <div class="media-right">
                        {% if user == object.author %}<button class="delete"></button>{% endif %}
                    </div>
                </article>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="columns">
        <div class="column is-8 is-offset-2 is-padding-y-30">
            {% include 'app/base/paginator.html' %}
        </div>
        {% endif %}
    </div>
</div>

<div class="container is-padding-y-30">
    <div class="columns">
        {% if user.is_authenticated %}
        <div class="column is-8 is-offset-2 is-padding-y-10">
            <div>
                <div id="commentPostBox">
                    <form action="{% url 'blog:add_comment' object.slug %}" method="post">
                        <div class="has-text-centered">
                            <h3 class="is-size-3">Hacer un comentario</h3>
                        </div>
                        <div>
                            <div>
                                {% csrf_token %}
                                {{ form.media }}
                                {{ form.as_p }}
                            </div>
                        </div>
                        <div>
                            <div class="control">
                                <button class="button is-primary is-fullwidth">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% else %}
        <div class="column is-8 is-offset-2 is-padding-y-10">
            <div>
                <div id="commentPostBox">
                    <div class="has-text-centered is-padding-y-10">
                        <h3 class="is-size-4">Para poder publicar debe estar registrado o iniciar sesión</h3>
                    </div>
                    <div class="is-centered is-padding-y-10">
                        <div class="buttons">
                            <a class="button is-primary is-outlined" href="{% url 'auth:login' %}?next={{ request.path }}">Iniciar Sesión</a>
                            <a class="button is-success is-outlined" href="{% url 'auth:register' %}?next={{ request.path }}">Registrarse</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block js %}
<script>
    // new WOW().init();
    // $( ".wow" ).addClass( "fadeInUp" );
</script>
{% endblock %}

                        

<div class="container_fluid">
                            <div class="row" id="newsletter">
                                <div class="col-12 text-center">
                                    <div class="card paral paralsec">
                                        <div class="card-body">
                                            <h5 class="card-title display-4">{{object.title}}</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="bg-light">
                            <div class="container">
                                <div class="row content-4 justify-center py-5">
                                    <div class="col-md-6 pl-5 pr-5 text-center">
                                        {% if object.img %}
                                            <img class="mb-4 img-fluid" src="{{object.img.url}}" alt="{{object.title}}">
                                        {% else %}
                                            <img class="mb-4 img-fluid" src="/static/base/img/img-base-m.png" alt="{{object.title}}">
                                        {% endif %}
                                    </div>
                                    <div class="col-md-6 text-left">
                                        <p class="card-text text-dark h2">{{object.sub_title}}.</p>
                                        {{object.text|safe}}
                                    </div>
                                    <div class="col">
                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if has_commentss %}
                            <div class="container">
                                {% for object in comments %}
                                    <div class="row justify-content-md-center coments">
                                        <div class="col-md-7 col-testimonial">
                                            <div class="row coment_body">
                                                <div class="col-3 col-sm-5 text-center">
                                                    <img class="" src="/static/base/img/base-s.png">
                                                </div>
                                                <div class="col-9 col-sm-7">
                                                    <div class="comment-body">
                                                        <p class="quote-text">
                                                            {{object.content|safe}}
                                                        </p>
                                                        <div class="footer">
                                                            <p><span class="quote-author">{{object.author}}</span></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                {% endfor %}
                                {% include 'app/base/paginator.html' %}
                            </div>
                        {% endif %}
                        
                        <div class="rgba-green-light">
                            <div class="container">
                                <div class="row justify-content-md-center -body">
                                    
                                    <div class="cta-3 text-center justify-center">
                                        {% if user.is_authenticated %}
                                            <div class="container">
                                                <a class="btn btn-lg btn-info py" data-toggle="modal" data-target="#fullHeightModalRight">Hacer un comentario</a>
                                            </div>
                                        {% else %}
                                            <div class="container">
                                                <h2 class="mb-4">Debe registrate o iniciar sesión para comentar en esta publicación</h2>
                                                <a class="btn btn-lg btn-success py" href="{% url 'auth:login' %}?next={{ request.path }}">Iniciar Sesión</a>
                                                <a class="btn btn-lg btn-primary py" href="{% url 'auth:register' %}?next={{ request.path }}">Registrarse</a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="modal fade top" id="fullHeightModalRight" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-full-height modal-bottom" role="document">
                                <div class="modal-content container">
                                    <form action="{% url 'blog:add_comment' object.slug %}" method="post">
                                        <div class="modal-header">
                                            <h5 class=" text-center" id="emyModalLabel">Hacer un comentario</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="text-center">
                                                {% csrf_token %}
                                                {{ form.media }}
                                                {{ form.as_p }}
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="text-center">
                                                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                                <button class="btn btn-success">Publicar
                                                    <i class="fa fa-paper-plane-o ml-1"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

templates/app/detail/departments_detail.html
{% extends 'app/base/index.html' %}{% load staticfiles %}

{% block css %}
<style>
    /* #breadcrumb{margin-top: 120px;} */
    .paralsec {
        /* margin-top: 75px; */
        {% if object.img %}
            background-image: url("{{object.background.url}}");
        {% else %}
            background-image: url("/static/base/img/img-base-l.png");
        {% endif %}
    }
    .card .card-body h5 {font-size: 5rem;margin-top: 50px;}
    .breadcrumb{margin-top: 15px;background-color: rgba(0, 0, 0, 0)}
    .item .content{
            padding-left: 10px;
            padding-top: 10px;
            height: 45px;
            width: 100%;
            background-color: #3f4236;
            box-shadow: -5px 4px black;
            text-shadow: -4px 3px 3px black;
        }
        .item{
            background: #FFF;
            box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
            margin-bottom: 45px;
        }
        .item .info{
            padding-left: 10px;
            padding-bottom: 10px;
            padding-right: 10px;
            padding-top: 10px;
        }
        .item img{
            text-align: center
        }
        .item .price{
            margin-right: 0px;
            margin-bottom: 0px;
            background-color: #8a7e5f;
            padding: 5px 20px 0px 20px;
            color: #FFF;
        }
</style>
{% endblock %}

{% block full_screen %}

{% endblock %}

{% block content %}
<div class="card paral paralsec view hm-black-slight">
    <div class="card-body mask">
    </div>
</div>
<div class="container">
    <div class="row" id="breadcrumb">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'sales:home' %}">Productos</a></li>
                <li class="breadcrumb-item"><a href="{% url 'sales:departments' %}">Departamentos</a></li>
                <li class="breadcrumb-item">{{object.name}}</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h1>
                {{object.name}}
            </h1>
            <hr class="special-color-dark mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <div class="service-body mb-5">
                {{object.description|safe}}
            </div>
        </div>
    </div>
    {% if products %}
        <div class="row my-5 justify-content-md-center">
            <div class="col-sm-12">
                <header class="text-center">
                    <h2 class="text-uppercase mb-5">
                        <a href="{% url 'sales:all' %}" class="text-dark">Nuestros productos</a>
                    </h2>
                </header>
            </div>
                {% for object in products %}
                    <div class="col-sm-4 align-self-center">
                        <div class="item">
                            <a href="{{object.get_absolute_url}}">
                                <img src="{% if object.img != '' %}/media/articulos/{{object.img}}{% else %}{% static 'base/img/base-m.png' %}{% endif %}" alt="{{object.name}}" class="img-fluid rounded mx-auto d-block"></img>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row my-5">
                <div class="col-12 ">
                    <div class="text-center">
                        <a href="{% url 'sales:all' %}" class="btn btn-outline-black text-white btn-lg">Ver más</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block js %}
<script>
    $('.service-body img').addClass('img-fluid')
</script>
{% endblock %}

templates/app/detail/product_details.html
{% extends 'app/base/index.html' %}{% load staticfiles %}{% load widget_tweaks %}

{% block css %}
<style>
    #serviceForm{
        background-color: #FFF;
        width: 80%;
        margin: 0 auto;
        padding: 1.9em 0;
        border-radius: 5px;
        box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
    }
    #serviceForm form{
        padding: 6px 20%;
    }
    #serviceForm form .field .control{
        width: 100%;
        border: solid 1px rgba(255,255,255,.8);
        background-color: #f5f5f5;
        padding: 5px;
        border-radius: 8px;
        margin-top: 25px
    }
    #serviceForm form button{width: 100%}

    #serviceForm form .field label {
        position: absolute;
        margin-top: -75px
    }
</style>
{% endblock %}

{% block full_screen %}

{% endblock %}

{% block content %}

<div class="container is-padding-top-30">
    <div class="columns">
        <div class="column is-8 is-offset-2">
            <div class="card box-animation">
                <div class="columns is-marginless is-centered">
                    <div class="column is-marginless">
                        <figure class="image">
                            <img src={{object.img.url}} alt={{object.code}}></img>
                        </figure>
                        
                    </div>
                    <div class="column is-padding-y-30">
                        <div class="">
                            <h1 class="is-size-4">
                                {{object.name}}
                            </h1>
                        </div>
                        <div class="">
                            <!-- <p class="is-size-5">
                                Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de
                                texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el
                                año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)
                                desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un
                                libro de textos especimen.
                            </p> -->
                            <p>Descripción: <strong>{{ object.description | safe }}</strong></p>
                            <p>Linea de producto: </p><p><strong>{{ object.line.name }}</strong></p>
                            <p>Categoría de producto: </p><p><strong>{{ object.category.name }}</strong></p>
                            <p>Codigo de producto: </p><p><strong>{{object.code}}</strong></p>
                            <p>Marca: </p><p><strong>{{object.brand.name}}</strong></p>
                            {% if object.sale %}<p>Antes: </p><p><strong>B./{{object.price_5}}</strong></p>{% endif %}
                            <p>Precio: </p><p><strong>B./{{object.price_4}}</strong></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <div class="column">
    <div class="" id="serviceForm">
        <form action="{% url 'services:detail' object.slug  %}?name={{object.name}}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="field">
                    {% if form.is_bound %}
                        {% if field.errors %}
                            {% render_field field class="control is-danger" %}
                                {% for error in field.errors %}
                                    <p class="help is-danger"><small>{{ error |safe }}<small</p>
                                {% endfor %}
                            {% else %}
                            % render_field field class="control is-valid" %}
                        {% endif %}
                        {% else %}
                            {% render_field field class="control" %}
                        {% endif %} 
                    {% if field.help_text %}
                        <p class="help is-success"><small>{{ field.help_text |safe}}</small></p>
                    {% endif %}
                    {{ field.label_tag | safe  }}
                </div>
            {% endfor %}
            <input type="hidden" name="service" value="{{object.name}}">
            
            <div class="control">
                <button class="button is-primary">Enviar</button>
            </div>
        </form>
    </div>
</div> -->
<div class="container is-padding-top-10">
    <div id="feeds">
        <div class="is-padding-top-60 has-text-centered">
            <h2 class="is-size-2">Productos relacionados</h2>
        </div>

        <div class="columns is-padding-top-50">
            {% for object in object_list %}
            {% if forloop.counter0 == 4 or forloop.counter0 == 8 or forloop.counter0 == 12 or forloop.counter0 == 16 %}</div><div class="columns">{% endif %}
            <div class="column is-2 {% if forloop.first or forloop.counter0 == 4 or forloop.counter0 == 7 %}is-offset-2{% endif %}">
                <div class="recent-feed">
                    <div class="feed-img">
                        <a href="{% url 'sales:product_detail' object.slug %}">
                            {% if object.img.url != None %}
                                <img src="{{object.img.url}}" alt="{{ object.code }}" class="image is-128-256" ></img>
                            {% else %}
                                <img src="/static/base/img/img-base-m.png" alt="{{ object.code }}" class="image is-128-256" ></img>
                            {% endif %}
                        </a>
                    </div>
                    <div class="feed-title">
                        <h3 class="is-size-7">
                            <a href="{% url 'sales:product_detail' object.slug %}" class="has-text-black">
                                {{ object.code }}
                            </a>
                        </h3>
                    </div>
                    <div class="feed-leyend is-clearfix">
                        <p class="is-size-7 is-pulled-left">
                            <span class="icon"><i class="fas fa-folder-open"></i></span>
                            {% if object.line != None %}    
                                <a href="{% url 'sales:all' %}?page=1&line={{object.line.id}}" class="has-text-black">{{ object.line.name | lower | capfirst }}</a>
                            {% elif object.category != None %}
                                <a href="{% url 'sales:all' %}?page=1&category={{object.category.id}}" class="has-text-black">{{ object.category.name | lower | capfirst }}</a>
                            {% else %}
                                <a href="{% url 'sales:all' %}?page=1&" class="has-text-black">{{ info_site.title | lower | capfirst }}</a>
                            {% endif %}
                        </p>
                    </div>
                    <div class="feed-content">
                        <div class="is-size-6">{{ object.description }}</div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="has-text-centered is-padding-top-60">
        </div>
    </div>
</div>

{{context}}
{% endblock %}

{% block js %}
{% endblock %}