src/api/urls.py
from django.conf import settings
from django.conf.urls import handler404,handler500,handler403,handler400
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flats
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.static import serve

from rest_framework import routers, views, serializers, status
from rest_framework.response import Response
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework_jwt.views import obtain_jwt_token

from src.api.views import viewset
from src.api.views.views import UserCreate, LoginAPI, UserAPI, CheckEmail, CheckUsername, UpdateViews

router = routers.DefaultRouter()
router.register(r'answers', viewset.AnswersViewSet)
router.register(r'brands', viewset.BrandsViewSet)
router.register(r'carousel-images', viewset.FrontendCarouselImageViewSet)
router.register(r'carousels', viewset.FrontendCarouselViewSet)
router.register(r'categories', viewset.CategoryViewSet)
router.register(r'colors', viewset.ColorViewSet)
router.register(r'comments', viewset.BlogPostCommetViewSet)
router.register(r'departments', viewset.DepartmentViewSet)
router.register(r'flatpages', viewset.FlatpagesViewSet)
router.register(r'groups', viewset.GroupViewSet)
router.register(r'lines', viewset.LineViewSet)
router.register(r'page-positions', viewset.PositionViewSet)
router.register(r'flat-pages', viewset.FlatpagesViewSet)
router.register(r'pages', viewset.PagesViewSet)
router.register(r'photos', viewset.PhotoViewSet)
router.register(r'posts', viewset.PublicBlogPostViewSet)
router.register(r'products', viewset.ArticleViewSet)
router.register(r'providers', viewset.ProviderViewSet)
router.register(r'questions', viewset.QuestionsViewSet)
router.register(r'services', viewset.ServiceViewSet)
router.register(r'site', viewset.SiteViewSet)
router.register(r'social-media', viewset.SocialMediaViewSet)
router.register(r'sub-lines', viewset.SubLineViewSet)
router.register(r'tags', viewset.BlogTagViewSet)
router.register(r'testimonials', viewset.TestimonialViewSet)
router.register(r'types', viewset.TypeViewSet)
router.register(r'types', viewset.TypeViewSet)
router.register(r'users', viewset.UserViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    # Token
    # path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('token/auth/', obtain_jwt_token),
    # path('/update-views/', UpdateViews, name='update-view'),
    # Auth
    # path('auth/user/', UserAPI.as_view(), name='register'),
    path('auth/register/', UserCreate.as_view(), name='register'),
    path('auth/login/', LoginAPI.as_view(), name='token_obtain_pair'),
    path('auth/check-email/', CheckEmail, name='register'),
    path('auth/check-username/', CheckUsername, name='register'),
    # path('/', include('rest_framework.urls', namespace='rest_framework')),
]

src/blog/urls.py
from django.urls import path, re_path, include
from .views import (
    Home,
    BlogDetail,
    comment_create,
)

app_name = 'blog'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('gracias', Home.as_view(), name='thanks'),
    path('<slug:slug>', BlogDetail.as_view(), name='blog_detail'),
    path('<slug:slug>/comentario/crear', comment_create, name='add_comment'),
]

src/intra/urls.py
from django.urls import (path, re_path, include)
from src.intra.views.base import *
from src.intra.views.blog import *
from src.intra.views.multimedia import *
from src.intra.views.sales import *
from src.intra.views.services import *
from src.intra.views.support import *
from src.intra.views.users import *

app_name = 'intra'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    
    path('blogs', Blog.as_view(), name='blog'),
    path('my-posts', MyBlog.as_view(), name='my-blog'),
    path('agregar/blog', BlogCreate.as_view(), name='blog-create'),
    path('actualizar/blog/<int:pk>/', BlogUpdate.as_view(), name='blog-update'),
    path('eliminar/blog/<int:pk>/', BlogDelete.as_view(), name='blog-delete'),

    path('comentarios', Comments.as_view(), name='comments'),
    path('agregar/comentario', CommentCreate.as_view(), name='comment-create'),
    path('actualizar/comentario/<int:pk>/', CommentUpdate.as_view(), name='comment-update'),
    path('eliminar/comentario/<int:pk>/', CommentDelete.as_view(), name='comment-delete'),

    path('etiquetas', Tags.as_view(), name='tags'),
    path('agregar/etiqueta', TagCreate.as_view(), name='tag-create'),
    path('actualizar/etiqueta/<int:pk>/', TagUpdate.as_view(), name='tag-update'),
    path('eliminar/etiqueta/<int:pk>/', TagDelete.as_view(), name='tag-delete'),

    path('configuraciones', Conf.as_view(), name='conf'),
    path('agregar/configuraciones', ConfCreate.as_view(), name='conf-create'),
    path('actualizar/configuraciones/<int:pk>/', ConfUpdate.as_view(), name='conf-update'),
    path('eliminar/configuraciones/<int:pk>/', ConfDelete.as_view(), name='conf-delete'),
    
    path('configuraciones/paginas', ConfPages.as_view(), name='conf-pages'),
    path('agregar/pagina', ConfPageCreate.as_view(), name='conf-page-create'),
    path('actualizar/pagina/<int:pk>/', ConfPageUpdate.as_view(), name='conf-page-update'),
    path('eliminar/pagina/<int:pk>/', ConfPageDelete.as_view(), name='conf-page-delete'),

    path('configuraciones/carruseles', ConfSlides.as_view(), name='conf-slides'),
    path('agregar/carrusel', ConfSlideCreate.as_view(), name='conf-slide-create'),
    path('actualizar/carrusel/<int:pk>/', ConfSlideUpdate.as_view(), name='conf-slide-update'),
    path('eliminar/carrusel/<int:pk>/', ConfSlideDelete.as_view(), name='conf-slide-delete'),
    path('agregar/carrusel-image', ConfSlideImgCreate.as_view(), name='conf-slide-img-create'),
    path('actualizar/carrusel-image/<int:pk>/', ConfSlideImgUpdate.as_view(), name='conf-slide-img-update'),
    path('eliminar/carrusel-image/<int:pk>/', ConfSlideImgDelete.as_view(), name='conf-slide-img-delete'),

    path('configuraciones/faq', ConfFAQS.as_view(), name='conf-faqs'),
    path('agregar/pregunta', ConfFAQQuestionCreate.as_view(), name='conf-faq-question-create'),
    path('actualizar/pregunta/<int:pk>/', ConfFAQQuestionUpdate.as_view(), name='conf-faq-question-update'),
    path('eliminar/pregunta/<int:pk>/', ConfFAQQuestionDelete.as_view(), name='conf-faq-question-delete'),
    path('agregar/respuesta', ConfFAQAnswerCreate.as_view(), name='conf-faq-answer-create'),
    path('actualizar/respuesta/<int:pk>/', ConfFAQAnswerUpdate.as_view(), name='conf-faq-answer-update'),
    path('eliminar/respuesta/<int:pk>/', ConfFAQAnswerDelete.as_view(), name='conf-faq-answer-delete'),

    path('configuraciones/newsletters', ConfNewsletters.as_view(), name='conf-newsletters'),
    path('agregar/newsletter', ConfNewsletterCreate.as_view(), name='conf-newsletter-create'),
    path('actualizar/newsletter/<int:pk>/', ConfNewsletterUpdate.as_view(), name='conf-newsletter-update'),
    path('eliminar/newsletter/<int:pk>/', ConfNewsletterDelete.as_view(), name='conf-newsletter-delete'),

    path('multimedias/', Medias.as_view(), name='medias'),
    path('agregar/multimedia', MediaCreate.as_view(), name='media-create'),
    path('actualizar/multimedia/<int:pk>/', MediaUpdate.as_view(), name='media-update'),
    path('eliminar/multimedia/<int:pk>/', MediaDelete.as_view(), name='media-delete'),

    path('perfil', Profile.as_view(), name='profile'),
    path('usuarios', Users.as_view(), name='users'),
    path('agregar/usuario', UserCreate.as_view(), name='user-create'),
    path('actualizar/usuario/<int:pk>/', UserUpdate.as_view(), name='user-update'),
    path('eliminar/usuario/<int:pk>/', UserDelete.as_view(), name='user-delete'),

    path('productos', Products.as_view(), name='products'),
    path('productos/top', TopProducts.as_view(), name='products-top'),
    path('agregar/producto', ProductCreate.as_view(), name='product-create'),
    path('actualizar/producto/<int:pk>/', ProductUpdate.as_view(), name='product-update'),
    path('eliminar/producto/<int:pk>/', ProductDelete.as_view(), name='product-delete'),

    path('productos/lineas', ProductLines.as_view(), name='products-lines'),
    path('agregar/linea', LineCreate.as_view(), name='line-create'),
    path('actualizar/linea/<int:pk>/', LineUpdate.as_view(), name='line-update'),
    path('eliminar/linea/<int:pk>/', LineDelete.as_view(), name='line-delete'),

    path('productos/sub-lineas', ProductSubLines.as_view(), name='products-sublines'),
    path('agregar/sublinea/', SubLineCreate.as_view(), name='subline-create'),
    path('actualizar/sub-linea/<int:pk>/', SubLineUpdate.as_view(), name='subline-update'),
    path('eliminar/sub-linea/<int:pk>/', SubLineDelete.as_view(), name='subline-delete'),
    
    path('productos/colores', ProductColor.as_view(), name='products-colors'),
    path('agregar/color', ColorCreate.as_view(), name='color-create'),
    path('actualizar/color/<int:pk>/', ColorUpdate.as_view(), name='color-update'),
    path('eliminar/color/<int:pk>/', ColorDelete.as_view(), name='color-delete'),
    
    path('productos/marcas', ProductBrand.as_view(), name='products-brands'),
    path('agregar/marca', BrandCreate.as_view(), name='brand-create'),
    path('actualizar/marca/<int:pk>/', BrandUpdate.as_view(), name='brand-update'),
    path('eliminar/marca/<int:pk>/', BrandDelete.as_view(), name='brand-delete'),
    
    path('productos/categorias', ProductCategory.as_view(), name='products-categories'),
    path('agregar/categoria', CategoryCreate.as_view(), name='category-create'),
    path('actualizar/categoria/<int:pk>/', CategoryUpdate.as_view(), name='category-update'),
    path('eliminar/categoria/<int:pk>/', CategoryDelete.as_view(), name='category-delete'),
    
    path('productos/departamentos', ProductDepartment.as_view(), name='products-departments'),
    path('agregar/departamento', DepartmentCreate.as_view(), name='department-create'),
    path('actualizar/departamento/<int:pk>/', DepartmentUpdate.as_view(), name='department-update'),
    path('eliminar/departamento/<int:pk>/', DepartmentDelete.as_view(), name='department-delete'),

    path('servicios', Services.as_view(), name='services'),    
    path('agregar/servicio', ServiceCreate.as_view(), name='service-create'),
    path('actualizar/servicio/<int:pk>/', ServiceUpdate.as_view(), name='service-update'),
    path('eliminar/servicio/<int:pk>/', ServiceDelete.as_view(), name='service-delete'),
    path('agregar/servicio-img', ServiceIMGCreate.as_view(), name='service-img-create'),
    path('actualizar/servicio-img/<int:pk>/', ServiceIMGUpdate.as_view(), name='service-img-update'),
    path('eliminar/servicio-img/<int:pk>/', ServiceIMGDelete.as_view(), name='service-img-delete'),

    path('soporte', Support.as_view(), name='support'),
]

src/user/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include

from .views import custom_login,custom_logout,custom_register, \
    ActivateAccountView, modal_cookie, error, thanks, newsletter,\
    activate, current_user, UserList

app_name = 'auth'
urlpatterns = [
    path('modal', modal_cookie, name='modal-cookie'),
    path('error', error, name='error'),
    path('newsletter', newsletter, name='newsletter'),
    path('gracias', thanks, name='thanks'),
    path('login/', custom_login, name='login'),
    path('salir/', custom_logout, name='logout'),
    path('registro/', custom_register, name='register'),
    path('password_reset/done/', auth_views.password_reset_done, 
        name='password_reset_done'
    ),
    path('password_reset_complete/done/', auth_views.password_reset_complete, 
        name='password_reset_complete'
    ),
    path('password_reset/', auth_views.password_reset, {
        'post_reset_redirect':'auth:password_reset_done',}, name='password_reset'
    ),
    re_path(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, 
        {
            'post_reset_redirect':'auth:password_reset_complete'
        },
        name='password_reset_confirm'
    ),
    re_path(r'^activar-cuenta/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ActivateAccountView.as_view(), name='activate_account'
    ),
    re_path(r'^activar/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'
    ),
    
    # JWT
    path('current_user/', current_user),
    path('users/', UserList.as_view()),
    
]

src/blog/forms.py
from django import forms
from django.contrib import admin
from ckeditor.widgets import CKEditorWidget

from .models import Comment

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget(), label="Comentario")

    class Meta:
        model = Comment
        fields = ('content',)
        labels = {
            'content':'Comentario',
        }

src/blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView,FormView

from .models import (Post, Comment)
from .forms import CommentForm

class Home(ListView):
    model = Post
    queryset = Post.objects.filter(draft=False)
    # context_object_name = 'boards'
    paginate_by = 6
    template_name = 'app/blog.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['SITE_URL'] = 'Ultimas noticias'
        context['has_newsletter'] = True
        context['url_nav'] = 'blog'

        return context


class BlogDetail(DetailView):

    model = Post
    template_name = 'app/detail/blog_detail.html'
    comments_paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['form'] = CommentForm
        context['url_nav'] = 'blog'
        
        comments = Comment.objects.filter(content_type=17, approved=True,object_id=context['object'].id)
        if comments.exists():
            context['has_comments'] = True
            context['comments'] = comments
        else:
            context['has_comments'] = False
        
        page = self.request.GET.get('page')
        comments_paginator = Paginator(comments, self.comments_paginate_by)
        try:
            comments_page_obj = comments_paginator.page(page)
            # context['is_paginated'] = True
        except (PageNotAnInteger, EmptyPage):
            comments_page_obj = comments_paginator.page(1)
        
        context['page_obj'] = comments_page_obj

        return context


@login_required 
def comment_create(request, slug):
    # return HttpResponseRedirect('/blog/%s' % slug)
    #obj = Comment.objects.get(id=id)
    obj = get_object_or_404(Post,slug=slug)

    if obj:
        post = obj
        author = request.user
        _content_type = obj.get_content_type
        object_id = obj.id


        form = CommentForm(request.POST)
    
        if form.is_valid():
            # content_type = ContentType.objects.get(model=_content_type)
            content_data = form.cleaned_data.get("content")

            new_comment = Comment.objects.get_or_create(
                author = request.user,
                content_type= _content_type,
                object_id = object_id,
                content = content_data,
                post = post,
                # parent = parent_obj,
            )
            return HttpResponseRedirect('/blog/%s' % slug)

        else:
            print('invalid')
            return HttpResponseRedirect('/blog/%s' % slug)

    return HttpResponseRedirect('/blog/%s' % slug)


def comment_delete(request, id):
    return HttpResponseRedirect('/')

src/faq/views.py
from django.shortcuts import render

# Create your views here.

src/intra/views/support.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_text, force_bytes
from django.views.generic import ListView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from src.user.tokens import account_activation_token
from src.blog.models import Post, Comment
from src.services.models import *
from src.ventas.models import *



@method_decorator(login_required, name='dispatch')
class Support(ListView):
    # model =
    # context_object_name = 'boards'
    queryset = ''
    template_name = 'intra/support.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['SITE_URL'] = 'Soporte'
        context['APP'] = 'Support'
        return context

templates/intra/create.html
{% extends 'intra/base/index.html' %}{% load staticfiles %}

{% block css %}
{% endblock %}

{% block content %}
<div class="app-dashboard-body-content off-canvas-content" data-off-canvas-content>
    
</div>
{% endblock %}

{% block js %}

{% endblock %}

templates/intra/delete.html
{% extends 'intra/base/index.html' %}{% load staticfiles %}

{% block css %}
{% endblock %}

{% block content %}
<div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-card">
        <form method="post">{% csrf_token %}
            <div class="modal-card-head">
                <p class="modal-card-title">Eliminar</p>
            </div>
            
            <div class="modal-card-body">
                <p class="is-size-4">¿Desea eliminar "{{ object }}"?</p>
            </div>

            <div class="modal-card-foot">
                <button class="button is-danger is-fullwidth">Eliminar</button>
            </div>
        </form>
    </div>
    <button class="modal-close is-large" aria-label="close" id="modalClose"></button>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function(){
        $(document).on('click','#modalClose', function(){
            var next = window.location.search.substring(1).split('next=')[1] || '/intra/';
            window.location = next;
        });
    });
</script>
{% endblock %}

templates/intra/faqs.html
{% extends 'intra/base/index.html' %}{% load staticfiles %}

{% block css %}
{% endblock %}

{% block crumbs %}
<li class="has-text-back"><a href="{% url 'intra:users' %}" aria-current="page">{{APP}}</a></li>
{% endblock %}

{% block content %}
<div class="card events-card">
    <header class="card-header">
        <p class="card-header-title">
            Preguntas
        </p>
        <p class="card-header-title">
            {% if user.profile.role == 'ADMIN' or user.profile.role == 'SUPERVISOR' or user.is_staff %}
            <a class="button is-small is-primary" href="{% url 'intra:conf-faq-question-create' %}?next={{ request.path }}">Agregar</a>
            {% endif %}
        </p>
    </header>
    <div class="card-table">
        <div class="content">
            <table class="table is-fullwidth is-striped">
                {% if not object_list %}
                <tbody>
                    <td class="is-centered"> <h3>No se han encontrado resultados</h3> </td>
                </tbody>
                {% else %}
                <thead>
                    <td>Título</td>
                    <td>Acciones</td>
                </thead>
                <tbody>
                    {% for post in object_list %}
                    <tr>
                        <td>{{post.title}}</td>
                        <td>
                            {% if user.profile.role == 'ADMIN' or user.profile.role == 'SUPERVISOR' or user.is_staff %}
                            <a class="button is-small is-primary" href="{% url 'intra:conf-faq-question-update' post.id %}?next={{ request.path }}"><span class="icon tooltip is-tooltip-left" data-tooltip="Editar"><i class="fas fa fa-edit"></i></span></a>
                            <a class="button is-small is-danger" href="{% url 'intra:conf-faq-question-delete' post.id %}?next={{ request.path }}"><span class="icon tooltip is-tooltip-right" data-tooltip="Eliminar"><i class="fas fa fa-eraser"></i></span></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% endif %}
            </table>
        </div>
    </div>
    <footer class="card-footer">
        <div class="content">
            {% include 'intra/base/paginator.html' %}
        </div>
    </footer>
</div>

<div class="card events-card">
    <header class="card-header">
        <p class="card-header-title">
            Respuestas
        </p>
        <p class="card-header-title">
            {% if user.profile.role == 'ADMIN' or user.profile.role == 'SUPERVISOR' or user.is_staff %}
            <a class="button is-small is-primary" href="{% url 'intra:conf-faq-answer-create' %}?next={{ request.path }}">Agregar</a>
            {% endif %}
        </p>
    </header>
    <div class="card-table">
        <div class="content">
            <table class="table is-fullwidth is-striped">
                {% if not answers %}
                <tbody>
                    <td class="is-centered"> <h3>No se han encontrado resultados</h3> </td>
                </tbody>
                {% else %}
                <thead>
                    <td>Pregunta</td>
                    <td>Respuesta</td>
                    <td>Acciones</td>
                </thead>
                <tbody>
                    {% for post in answers %}
                    <tr>
                        <td>{{post.question.title}}</td>
                        <td>{{post.text | safe}}</td>
                        <td>
                            {% if user.profile.role == 'ADMIN' or user.profile.role == 'SUPERVISOR' or user.is_staff %}
                            <a class="button is-small is-primary" href="{% url 'intra:conf-faq-answer-update' post.id %}?next={{ request.path }}"><span class="icon tooltip is-tooltip-left" data-tooltip="Editar"><i class="fas fa fa-edit"></i></span></a>
                            <a class="button is-small is-danger" href="{% url 'intra:conf-faq-answer-delete' post.id %}?next={{ request.path }}"><span class="icon tooltip is-tooltip-right" data-tooltip="Eliminar"><i class="fas fa fa-eraser"></i></span></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% endif %}
            </table>
        </div>
    </div>
    <footer class="card-footer">
        <div class="content">
            {% include 'intra/base/paginator.html' %}
        </div>
    </footer>
</div>
{% endblock %}

{% block js %}

{% endblock %}

templates/intra/medias.html
{% extends 'intra/base/index.html' %}{% load staticfiles %}

{% block css %}
{% endblock %}

{% block content %}
<div class="app-dashboard-body-content off-canvas-content" data-off-canvas-content>
    
</div>
{% endblock %}

{% block js %}

{% endblock %}

templates/intra/services.html
{% extends 'intra/base/index.html' %}{% load staticfiles %}

{% block css %}
{% endblock %}

{% block crumbs %}
<li class="has-text-back"><a href="{% url 'intra:services' %}" aria-current="page">Servicios</a></li>
{% endblock %}

{% block content %}
<div class="card events-card">
    <header class="card-header">
        <p class="card-header-title">
            Servicios
        </p>
        <p class="card-header-title">
            {% if user.profile.role == 'ADMIN' or user.profile.role == 'SUPERVISOR' or user.is_staff %}
            <a class="button is-small is-primary" href="{% url 'intra:service-create' %}?next={{ request.path }}">Agregar</a>
            {% endif %}
        </p>
    </header>
    <div class="card-table">
        <div class="content">
            <table class="table is-fullwidth is-striped">
                {% if not object_list %}
                <tbody>
                    <td class="is-centered"> <h3>No se han encontrado resultados</h3> </td>
                </tbody>
                {% else %}
                <thead>
                    <td>ID</td>
                    <td>Nombre</td>
                    <td>Descripción</td>
                    <td>Acciones</td>
                </thead>
                <tbody>
                    {% for service in object_list %}
                    <tr>
                        <td width="5%">{{service.id}}</td>
                        <td><p>{{service.name}}</p></td>
                        <td><p><span>{{service.content | safe}}</span></p></td>
                        <td>
                            {% if user.profile.role == 'ADMIN' or user.profile.role == 'SUPERVISOR' or user.is_staff %}
                            <a class="button is-small is-primary" href="{% url 'intra:service-update' pk=service.id %}?next={{ request.path }}"><span class="icon tooltip is-tooltip-left" data-tooltip="Editar"><i class="fas fa fa-edit"></i></span></a>
                            <a class="button is-small is-danger" href="{% url 'intra:service-delete' pk=service.id %}?next={{ request.path }}"><span class="icon tooltip is-tooltip-right" data-tooltip="Eliminar"><i class="fas fa fa-eraser"></i></span></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% endif %}
            </table>
        </div>
    </div>
    <footer class="card-footer">
        <div class="content">
            {% include 'intra/base/paginator.html' %}
        </div>
    </footer>
</div>

<div class="card events-card">
    <header class="card-header">
        <p class="card-header-title">
            Servicios
        </p>
        <p class="card-header-title">
            {% if user.profile.role == 'ADMIN' or user.profile.role == 'SUPERVISOR' or user.is_staff %}
            <a class="button is-small is-primary" href="{% url 'intra:service-img-create' %}?next={{ request.path }}">Agregar</a>
            {% endif %}
        </p>
    </header>
    <div class="card-table">
        <div class="content">
            <table class="table is-fullwidth is-striped">
                {% if not images %}
                <tbody>
                    <td class="is-centered"> <h3>No se han encontrado resultados</h3> </td>
                </tbody>
                {% else %}
                <thead>
                    <td>Servicio</td>
                    <td>Imagen</td>
                    <td>Nombre</td>
                    <td>Contenido</td>
                    <td>Acciones</td>
                </thead>
                <tbody>
                    {% for service in images %}
                    <tr>
                        <td width="5%">{{service.Service.name}}</td>
                        <td>
                            {% if service.image.url != None %}
                            <figure class="image is-64x64">
                                <img src="{{service.image.url}}" alt="{{service.Service.name}}">
                            </figure>
                            {% else %}
                            {{service.image}}
                            {% endif %}
                        </td>
                        <td>{{service.name}}</td>
                        <td>{{service.text | safe}}</td>
                        <td>
                            {% if user.profile.role == 'ADMIN' or user.profile.role == 'SUPERVISOR' or user.is_staff %}
                            <a class="button is-small is-primary" href="{% url 'intra:service-img-update' pk=service.id %}?next={{ request.path }}"><span class="icon tooltip is-tooltip-left" data-tooltip="Editar"><i class="fas fa fa-edit"></i></span></a>
                            <a class="button is-small is-danger" href="{% url 'intra:service-img-delete' pk=service.id %}?next={{ request.path }}"><span class="icon tooltip is-tooltip-right" data-tooltip="Eliminar"><i class="fas fa fa-eraser"></i></span></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% endif %}
            </table>
        </div>
    </div>
    <footer class="card-footer">
        <div class="content">
            {% include 'intra/base/paginator.html' %}
        </div>
    </footer>
</div>
{% endblock %}

{% block js %}

{% endblock %}